name: currency_exchange  # Name of your project

version: 1.0.0

config-version: 2

profile: default  # The profile you are using for connections

target-path: "target"  # Directory for compiled files
clean-targets:
  - "target"
  - "dbt_packages"

models:
  currency_exchange:  # This must match the project `name`
    dwh:
      database: analytics
      materialized: incremental
