name: currency_exchange  # Name of your project

version: 1.0.0

config-version: 2

profile: default

target-path: "target"  # Directory for compiled files
clean-targets:
  - "target"
  - "dbt_packages"

models:
  currency_exchange:  
    dwh:
      database: analytics
      materialized: incremental 
    exchange_rate_trends:  
      +materialized: view  